### ISSUE TITLE
Serial write HEX data

### ISSUE THREAD

**Issue by seeya** [green-green-avk/AnotherTerm#18]
I'm trying to use the serial command which $TERMSH provides and it does work well for normal text characters.
Is it possible to have a HEX mode? When I use the app "Serial USB Terminal" from the PlayStore, there is a setting to set "Text" or "HEX" mode. 

My goal is to proxy requests over HTTP to Serial which will be very convenient and efficient rather than implementing it in Java/Kotlin for specific apps.

**Comment by green-green-avk** [comment]
🤔...

`termsh serial` just passes any binary data via its stdin/stdout as is. So, I see this requirement out of scope of this particular **termsh** command.
You can:
1) `echo -e` + some scripting (see man page).
2) **Python** under **PRoot**.
  See:
  * Example: <https://green-green-avk.github.io/AnotherTerm-docs/#shell-features>
  * About **PRoot**: <https://green-green-avk.github.io/AnotherTerm-docs/installing-linux-under-proot.html#main_content>

What do you think?

Maybe I need better understanding of your task to provide a better answer...

**Comment by seeya** [comment]
Thank you for the suggestions, I apologize in not being clear.

What I did was to modify the codes in `TermSh.java` to test.
I changed the following lines from `1684` to something like this.
It worked but it would be better not to modify the source code if an alternative works. Maybe I can try your suggestion `1. echo -e` which converts directly. 

### Original
https://github.com/green-green-avk/AnotherTerm/blob/3553b2ab7cc79a7e3540955ff7aeef17ecf7a07c/app/src/main/java/green_green_avk/anotherterm/TermSh.java#L1684-L1690

### Modified
```java
 try { 
      while (true) {
        final int r = shellCmd.stdIn.read(buf);
        if (r < 0) break;
        String v = new String(buf, StandardCharsets.UTF_8);
        byte[] hexBuf = fromHexString(v);
        toBe.write(hexBuf);
     } 
 } catch (final IOException | BackendException e) { 
```

**Comment by green-green-avk** [comment]
By the way, how your code organised that it requires such an exotic approach?
What doesn't work if you just run it as `<your_program> | termsh serial ...`? What bytes are lost?

**Comment by seeya** [comment]
Honestly I did it this way because I have an Android app previously which took a String and used the `fromHexString` method to write to the USB and it worked. 

Also I am inexperienced in this and still trying to understand the conversion from a Hex String to a ByteArray.
I will do a test tomorrow as the device is not with me. But with your suggestion, I think I have a better idea of how to proceed.

**Comment by green-green-avk** [comment]
Technically, you can install **Alpine** under **PRoot** as it is reasonably small.
You will have **python** and **ssh** server for remote management as a bonus.

**Comment by green-green-avk** [comment]
Just an example of simple HTTP <=> `termsh serial` server to be executed under a PRooted Linux: <https://gist.github.com/green-green-avk/93fb12169a3333823c40740c634fb2ce>

**Comment by seeya** [comment]
> Just an example of simple HTTP <=> `termsh serial` server to be executed under a PRooted Linux: https://gist.github.com/green-green-avk/93fb12169a3333823c40740c634fb2ce
> 
> To read: `http://<host:port>/readbytes` (behaves as described in https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format)
> To write: `http://<host:port>/writebytes/<hexidecimalstring>`

Thank you for taking the time to write the example codes. 
With your suggestions I installed **Alpine** under **PRoot** and ran the script `python server.py`.
It works perfectly! The code `bytes.fromhex()` works without losing any bytes.

I'm looking to start the script on boot. I've seen the documentation at https://green-green-avk.github.io/AnotherTerm-docs/start-a-session-by-an-intent.html#main_content. But as for my case, is there a way to "remember" the settings for the permission prompt for USB? So that it will not require any user intervention at the start.

**Comment by green-green-avk** [comment]
Unfortunately, the "manual" USB permission is an Android limitation. 😥

**Comment by seeya** [comment]
> Unfortunately, this "manual" USB permission granting is an unconditional Android limitation. Google knows better... 😡

I managed to sort of bypass that by modifying the `AndroidManifest.xml` with the following `intent-filter`.

```
        <activity
            android:name=".SessionsActivity"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <intent-filter>
                <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"/>
            </intent-filter>
            <meta-data
                android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"
                android:resource="@xml/device_filter" />
        </activity>
```

And adding the `device_filter.xml` file under `res/xml`.

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- 0x0403 / 0x60??: FTDI -->
    <usb-device vendor-id="1027" product-id="24577" /> <!-- 0x6001: FT232R -->
    <usb-device vendor-id="1027" product-id="24592" /> <!-- 0x6010: FT2232H -->
    <usb-device vendor-id="1027" product-id="24593" /> <!-- 0x6011: FT4232H -->
    <usb-device vendor-id="1027" product-id="24596" /> <!-- 0x6014: FT232H -->

    <!-- 0x10C4 / 0xEA??: Silabs CP210x -->
    <usb-device vendor-id="4292" product-id="60000" /> <!-- 0xea60: CP2102 -->
    <usb-device vendor-id="4292" product-id="60016" /> <!-- 0xea70: CP2105 -->
    <usb-device vendor-id="4292" product-id="60017" /> <!-- 0xea71: CP2108 -->
    <usb-device vendor-id="4292" product-id="60032" /> <!-- 0xea80: CP2110 -->

    <!-- 0x067B / 0x2303: Prolific PL2303 -->
    <usb-device vendor-id="1659" product-id="8963" />

    <!-- 0x1a86 / 0x?523: Qinheng CH34x -->
    <usb-device vendor-id="6790" product-id="21795" /> <!-- 0x5523: CH341A -->
    <usb-device vendor-id="6790" product-id="29987" /> <!-- 0x7523: CH340 -->

    <!-- CDC driver -->
    <usb-device vendor-id="9025" />                   <!-- 0x2341 / ......: Arduino -->
    <usb-device vendor-id="5824" product-id="1155" /> <!-- 0x16C0 / 0x0483: Teensyduino  -->
    <usb-device vendor-id="1003" product-id="8260" /> <!-- 0x03EB / 0x2044: Atmel Lufa -->
    <usb-device vendor-id="7855" product-id="4"    /> <!-- 0x1eaf / 0x0004: Leaflabs Maple -->
    <usb-device vendor-id="3368" product-id="516"  /> <!-- 0x0d28 / 0x0204: ARM mbed -->
</resources>
```

When I plug in a USB device, a prompt will show "AnotherTerm" as an option. There will also be a checkbox to "Always Open With". With that, whenever I plug in a USB, it will open "AnotherTerm" and running the command `$TERMSH serial` won't show the permission prompt anymore.

**Comment by green-green-avk** [comment]
The main question seems resolved.
