### ISSUE TITLE
On containers-debian-buster (root) error on command ps

### ISSUE THREAD

**Issue by GitHubOpenIssue** [green-green-avk/AnotherTerm#2]
root@localhost:~# ps
Error: /proc must be mounted
   To mount /proc at boot you need an /etc/fstab line li
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
root@localhost:~#

**Comment by green-green-avk** [comment]
Google blocked most of the `/proc` since Android 8. So, it's "by design".

**Comment by GitHubOpenIssue** [comment]
It's working on Alpine..

**Comment by green-green-avk** [comment]
It seems, Alpine busybox `ps` has a bit different implementation and can work with these restrictions.
