### ISSUE TITLE
.bashrc .shrc or other

### ISSUE THREAD

**Issue by gintarasmartinaitis** [green-green-avk/AnotherTerm#20]
Привет всем,
в какой файл надо записывать alias? Просто у  меня так
![Screenshot_20210903-185150](https://user-images.githubusercontent.com/27124319/132034171-468bc4a5-4c96-4f3c-8c12-64bd67d0b23d.png)
не работает.  Прошу прощения если что не так.
С уважением Gintaras Martinaitis.

**Comment by green-green-avk** [comment]
`alias` can be set for a particular shell interpreter instance and IS NOT derived by any other its instance launched from it.

A shell startup script should be used to set aliases automatically. See below.

- If it is about Android own environment (not **PRoot**ed), you can face either ksh or ash the shell interpreter. Both of them use an `ENV` environment variable to set a default startup script for each shell execution (not only the login one).

  So, just:
  1) create, to say, a `$DATA_DIR/.sh.rc`
  2) add `export ENV="$DATA_DIR/.sh.rc"` into the "execute" 
  field of your favorite:
  ![Screenshot_20210903-090511_Another Term (Debug)~2](https://user-images.githubusercontent.com/45503261/132274511-29f7a993-eec7-4e5b-97b8-b6797f3d3a21.jpg)
  3) put what you wish into the `$DATA_DIR/.sh.rc`
  4) ???
  5) Profit.


- If it is about some environment running under **PRoot**, I think, you would wish to use bash, so the only thing you need is to edit a `.bashrc` in your environment's home directory.

**Comment by green-green-avk** [comment]
The main question seems resolved.
