### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [green-green-avk/AnotherTerm#3]
With your app being open source and free of trackers: would you consider making it available outside the walled garden of Google Play as well, e.g. by attaching it to your `releases/` here – for those who cannot (Huawei devices) or do not want to ("tin foils") access Play Store? Thanks in advance!

**Comment by green-green-avk** [comment]
Thank you for the advice.
I'll add it into the assets of each release from now on:
<https://github.com/green-green-avk/AnotherTerm/releases/tag/MkIIIn_release>

**Comment by IzzySoft** [comment]
Thanks a lot! Will try it soon. This might replace JuiceSSH for me :smiley:
