### ISSUE TITLE
About wayland scanner (scan.py) and source generating

### ISSUE THREAD

**Issue by twaik** [green-green-avk/AnotherTerm#32]
Hi.
I found out you are using pre-generated java files. I think you can try to generate them on demand.
To do this you can rewrite scan.py in Java or Groovy. I did [this](https://gist.github.com/twaik/563ea91526dccd15e2bf5974d5d3ef10) for my project. This script can be included from build.gradle.
Close this if you are not interested.

**Comment by green-green-avk** [comment]
Good catch!
Rebuilding of these Java files is extremely rare and potentially selective though...

**Comment by twaik** [comment]
Stale issue.
