### ISSUE TITLE
Terminal color is too dark to see

### ISSUE THREAD

**Issue by zongou** [green-green-avk/AnotherTerm#35]
terminal shows gray for white, and darker blue for blue and makes the status bar of nnn nearly invisible
![Screenshot_2022-12-21-05-03-24-689_green_green_avk anotherterm oldgood](https://user-images.githubusercontent.com/23202896/208766363-1303ea3e-f72d-4330-948d-ce87db4b52df.jpg)
![Screenshot_2022-12-21-05-03-02-214_com termux](https://user-images.githubusercontent.com/23202896/208766410-da73b25f-98be-4bbf-a27d-d780ba83695c.jpg)

**Comment by green-green-avk** [comment]
I took a time for this bug finally posted...

Ok, I'll implement it.

**Comment by green-green-avk** [comment]
BTW, too bright regular blue could make eyes bleeding: just try **Midnight Commander** for example.
I wonder, why the author did not make this text bold - all terminals make it bright (not only bold) in this case.
(And, what's more important, why does the `NNN_COLORS` not provide a way to configure it bold?)

Anyways, you could just set `TERM=xterm-256color` and set the color to any 8-bit indexed value [via `NNN_COLORS`](https://manpages.debian.org/testing/nnn/nnn.1.en.html#ENVIRONMENT).
*See the color numbers [here](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) (or [here](https://user-images.githubusercontent.com/1482942/93023823-46a6ba80-f5e1-11ea-9ea3-6a3c757704f4.png) as recommended by the author).*

**Comment by zongou** [comment]
![Screenshot_2022-12-28-14-44-41-975_com termux](https://user-images.githubusercontent.com/23202896/209770838-8ea42992-3eb7-43cb-8dbd-108e862f902c.jpg)
![Screenshot_2022-12-28-14-44-17-915_green_green_avk anotherterm oldgood](https://user-images.githubusercontent.com/23202896/209770855-4543ff2e-a0dd-4237-8b46-ed9450178a71.jpg)
https://github.com/V01dDweller/color-tests
anotherterm does not handle color well

**Comment by zongou** [comment]
i have used custom color for nnn after i posted this issue, to make status bar visible

**Comment by zongou** [comment]
> BTW, too bright regular blue could make eyes bleeding: just try **Midnight Commander** for example. I wonder, why the author did not make this text bold - all terminals make it bright (not only bold) in this case. (And, what's more important, why does the `NNN_COLORS` not provide a way to configure it bold?)
> 
> Anyways, you could just set `TERM=xterm-256color` and set the color to any 8-bit indexed value [via `NNN_COLORS`](https://manpages.debian.org/testing/nnn/nnn.1.en.html#ENVIRONMENT). _See the color numbers [here](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) (or [here](https://user-images.githubusercontent.com/1482942/93023823-46a6ba80-f5e1-11ea-9ea3-6a3c757704f4.png) as recommended by the author)._

![Screenshot_2022-12-28-15-04-15-565_green_green_avk anotherterm oldgood](https://user-images.githubusercontent.com/23202896/209772290-9e88c5c4-5afc-40f0-afec-1cced75aa738.jpg)

font style is in bold by default

**Comment by green-green-avk** [comment]
> anotherterm does not handle color well

A long time ago, I decided to save some memory, so the color attributes are packed in a pretty insane manner now: the upcoming update will fix it.

**Comment by green-green-avk** [comment]
Does it look better now?
Please, recheck.

**Comment by zongou** [comment]
it is better now, thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
