### ISSUE TITLE
Built-in command to operate android clipboard

### ISSUE THREAD

**Issue by zongou** [green-green-avk/AnotherTerm#36]
since such command has not been implemented, when copying text from terminal you will encounter some problems, for instance, with micro editor, you will be copying line numbers and the chopped text shown on screen. thus currently i have written a plugin for micro editor to copy selection to android clipboard.

https://github.com/zongou/micro-androidtool
clone and place that plugin dir in ~/.config/micro/plug/
![copy_text_within_micro_editor](https://user-images.githubusercontent.com/23202896/212621275-08102bd8-170b-4601-8255-4801f4365fc4.gif)

and a command tool
https://gist.github.com/zongou/5a6a6e58c2cc621209ce259e224cdb78
![command_tool](https://user-images.githubusercontent.com/23202896/212621318-e8d151a8-aa72-46b1-88f9-a91c6f41f78d.gif)

**Comment by zongou** [comment]
https://user-images.githubusercontent.com/23202896/212481334-b71877c8-d2dd-4367-b9f1-6de85af79c0b.mp4

**Comment by green-green-avk** [comment]
🤔... Yes. And one more local shell permission for it.

**Comment by green-green-avk** [comment]
Ready: <https://green-green-avk.github.io/AnotherTerm-docs/local-shell-utility.html#cmd_clipboard-copy>

Please, confirm.

**Comment by zongou** [comment]
> Ready: https://green-green-avk.github.io/AnotherTerm-docs/local-shell-utility.html#cmd_clipboard-copy
> 
> Please, confirm.

thanks, it works
