### ISSUE TITLE
With Font iconsolata not display completely

### ISSUE THREAD

**Issue by zongou** [green-green-avk/AnotherTerm#37]
![Screenshot_2023-01-24-18-48-55-511_green_green_avk anotherterm oldgood](https://user-images.githubusercontent.com/23202896/214273477-14c4a397-622e-42a1-b340-a4ef751cf240.jpg)
bottom part of character is hidden, especially for character gjpq

**Comment by green-green-avk** [comment]
[`Paint.getFontSpacing()`](https://developer.android.com/reference/android/graphics/Paint#getFontSpacing()) is currently used to determine the line height. I wonder why the monospace font has such a strange metrics...

Possibly, I need to change the rendering order a bit...

**Comment by green-green-avk** [comment]
Fixed.
Please, confirm.

**Comment by zongou** [comment]
> Fixed. Please, confirm.
Thank, it's fixed
