### ISSUE TITLE
A mask is displayed when Returning back to terminal

### ISSUE THREAD

**Issue by zongou** [green-green-avk/AnotherTerm#38]
https://user-images.githubusercontent.com/23202896/217412121-b85f290a-3073-4a79-a650-c3465f813331.mp4

AnotherTerm version: MkIV-dev36
device: mi8(dipper)
android version: 10

**Comment by green-green-avk** [comment]
Yep. It's very rare on Android&nbsp;9 due to its different rendering pipeline. That's how I missed it so badly...
The fix is almost there...

**Comment by green-green-avk** [comment]
It was an oof size one...

Fixed.
Please, confirm.

**Comment by zongou** [comment]
> It was an oof size one...
> 
> Fixed. Please, confirm.

thanks, its fixed
