### ISSUE TITLE
Text direction

### ISSUE THREAD

**Issue by av10one** [green-green-avk/AnotherTerm#46]
Connecting to a VT220 telnet host displaying Hebrew language, the text displayed in the wrong direction - 

![image](https://github.com/green-green-avk/AnotherTerm/assets/65309780/ffb434c8-0bfd-4bee-bf5c-9c6555bfe2dd)

Trying this with another app, it displayed correctly - 

![image](https://github.com/green-green-avk/AnotherTerm/assets/65309780/339af7c0-5dad-4d02-ad12-ed8c1929acfc)

It'll be great if you could fix it.
To reproduce this I captured this screen to a file - 
[1.txt](https://github.com/green-green-avk/AnotherTerm/files/12643643/1.txt)
Then sent it as HEX to the app.

Thanks

**Comment by green-green-avk** [comment]
`konsole`:

<img alt="Screenshot_20230923_161953" src="https://github.com/green-green-avk/AnotherTerm/assets/45503261/633ab8aa-469a-40a4-8441-ace0942786e7">

`xterm`:

<img alt="Screenshot_20230923_162132" src="https://github.com/green-green-avk/AnotherTerm/assets/45503261/6ad714c0-8f36-4c1e-ba22-5faa098daceb">

🤔 I'll try to support.

**Comment by av10one** [comment]
While I don't think I can assist with coding, if you feel I can help in other aspects, see me as fully committed😁.

**Comment by green-green-avk** [comment]
Should be fixed now...

The *Raw Mode* is here now (see details in the built-in help):

*Global default option*
![Screenshot_20231112-160114_Another Term (Debug)](https://github.com/green-green-avk/AnotherTerm/assets/45503261/3e952f1c-7976-42d8-abac-ec3d6e628822)

*Per-profile*
![Screenshot_20231112-160436_Another Term (Debug)](https://github.com/green-green-avk/AnotherTerm/assets/45503261/25125ee5-afcf-4d55-8191-3aff778f672b)

*During session*
![Screenshot_20231112-160548_Another Term (Debug)](https://github.com/green-green-avk/AnotherTerm/assets/45503261/1c01494b-0db3-4f7c-aca3-06f64cccc115)

**Comment by av10one** [comment]
Is non-monospace character length bug makes it look not alligned like this

![image](https://github.com/green-green-avk/AnotherTerm/assets/65309780/29192947-ed38-4d74-931e-49a3c18d854d)

**Comment by green-green-avk** [comment]
Yes.

**Comment by green-green-avk** [comment]
https://github.com/green-green-avk/AnotherTerm/issues/50#issuecomment-1845607679
