### ISSUE TITLE
Non-monospace characters rendering

### ISSUE THREAD

**Issue by green-green-avk** [green-green-avk/AnotherTerm#50]
Is non-monospace character length bug makes it look not alligned like this

![image](https://github.com/green-green-avk/AnotherTerm/assets/65309780/29192947-ed38-4d74-931e-49a3c18d854d)

_Originally posted by @av10one in https://github.com/green-green-avk/AnotherTerm/issues/46#issuecomment-1817835512_

**Comment by green-green-avk** [comment]
Fixed. Please, check.

**Comment by av10one** [comment]
Looks good -

![image](https://github.com/green-green-avk/AnotherTerm/assets/65309780/16e7f6ba-73fd-4d64-b88f-ee612b75c5d2)

Thanks!
